spring:
  application:
    name: api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #?? ??? (??): ?? ?? ??? ?????, application.yml ??? ?? ?? ?? ????? ???
  #${DB_PASSWORD}?? ?? ?? ?? ??? ??? ???.
  #
  ## ??? ??? ?? ??
  #spring:
  #  datasource:
  #    url: jdbc:postgresql://db.jctcovjbmmlikoduwapk.supabase.co:5432/postgres?user=postgres&password=${DB_PASSWORD}